[tool.poetry]
name = "loan-fintech-api"
version = "0.1.0"
description = "ğŸ’³ â˜ï¸ Another Loan Fintech API"
authors = ["Leonardo Gregianin <leogregianin@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
django = "3.2.18"
djangorestframework = "^3.13.1"
dj-database-url = "^0.5.0"
whitenoise = "^6.1.0"
django-cors-headers = "^3.12.0"
drf-yasg = "^1.20.0"
djangorestframework-simplejwt = "^5.1.0"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
codecov = "^2.1.12"
black = "^22.3.0"
pre-commit = "^2.19.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
